# Generated by Django 5.2 on 2025-05-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_user2_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
