# Generated by Django 5.2 on 2025-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_delete_user2_alter_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_country', models.CharField(max_length=50)),
                ('property_street', models.CharField(max_length=255)),
                ('property_city', models.CharField(max_length=255)),
                ('property_postal', models.CharField(max_length=255)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('property_description', models.TextField()),
                ('property_rooms', models.IntegerField()),
                ('property_bedrooms', models.IntegerField()),
                ('property_bathrooms', models.IntegerField()),
                ('property_square_meters_size', models.DecimalField(decimal_places=3, max_digits=10)),
                ('property_sold_status', models.BooleanField()),
            ],
        ),
    ]
