# Generated by Django 5.2 on 2025-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='propert_images/'),
        ),
    ]
