# Generated by Django 5.2 on 2025-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_userprofile_bio_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
