# Generated by Django 5.2.1 on 2025-05-12 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('position', models.IntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app2.properties')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerprice', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('status', models.TextField()),
                ('create_at_time', models.DateTimeField()),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, to='app2.userprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.properties')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('postal', models.TextField()),
                ('country', models.TextField()),
                ('national_pid', models.TextField()),
                ('pay_method', models.TextField()),
                ('card_name', models.TextField()),
                ('card_num', models.TextField()),
                ('expiration_date_card', models.TextField()),
                ('cvc', models.TextField()),
                ('bank_acc', models.TextField()),
                ('mortgage_prov', models.TextField()),
                ('confirm_time', models.DateTimeField()),
                ('purchase_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.purchaseoffer')),
            ],
        ),
    ]
