# Generated by Django 5.2.1 on 2025-05-13 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_propertyimage_purchaseoffer_finalizedoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acc_made_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='alpha_user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
