# Generated by Django 5.2.1 on 2025-05-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_userprofile_acc_made_time_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedoffer',
            name='card_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='cvc',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='national_pid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='postal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
