# Generated by Django 5.2 on 2025-05-13 12:51

import app2.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_alter_finalizedoffer_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedoffer',
            name='cvc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=app2.utils.uploads.upload_to_profile),
        ),
    ]
