# Generated by Django 5.2 on 2025-05-13 15:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_finalizedoffer_cvc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseoffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseoffer',
            unique_together={('property', 'buyer')},
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseoffer',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseoffer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='app2.properties'),
        ),
        migrations.AlterField(
            model_name='purchaseoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contingent', 'Contingent'), ('finalized', 'Finalized')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='purchaseoffer',
            name='create_at_time',
        ),
        migrations.RemoveField(
            model_name='purchaseoffer',
            name='offerprice',
        ),
    ]
