# Generated by Django 5.2 on 2025-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_properties_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['position', 'pk']},
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sort order: lower numbers come first.'),
        ),
    ]
