# Generated by Django 5.2 on 2025-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment'), ('castle', 'Castle')], default='house', help_text='When this property was first added to the listings.', max_length=20),
        ),
    ]
