# Generated by Django 5.2 on 2025-05-14 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_properties_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='listed_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('house', 'House'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment'), ('castle', 'Castle')], default='house', help_text='most fitting description.', max_length=20),
        ),
    ]
