# Generated by Django 5.2 on 2025-05-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_properties_listed_at_alter_properties_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalizedoffer',
            old_name='street',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='finalizedoffer',
            old_name='postal',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='finalizedoffer',
            name='card_name',
        ),
        migrations.AddField(
            model_name='finalizedoffer',
            name='cardholder_name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalizedoffer',
            name='property',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app2.properties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalizedoffer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='card_num',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='confirm_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='expiration_date_card',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='mortgage_prov',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finalizedoffer',
            name='pay_method',
            field=models.CharField(max_length=255),
        ),
    ]
