# Generated by Django 5.2.1 on 2025-05-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_rename_street_finalizedoffer_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('agency', 'Real Estate Agency')], max_length=20, null=True),
        ),
    ]
