# Generated by Django 5.2 on 2025-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_userprofile_seller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('individual', 'Individual'), ('agency', 'Real Estate Agency')], max_length=20, null=True),
        ),
    ]
